name: pelion-edge-tools
base: core20
version: '0.8'
summary: Tools for debugging Pelion Edge
description: |
  Tools for debugging Pelion Edge.

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  test-bootstrap:
    command: bin/test-bootstrap.sh
  test-lwm2m:
    command: bin/test-lwm2m.sh

parts:
  credentials:
    plugin: dump
    source: credentials/
    organize:
      '*': credentials/
  scripts:
    plugin: dump
    source: scripts/
    organize:
      test-bootstrap.sh: bin/
      test-lwm2m.sh: bin/
