name: edge-tools
base: core20
version: '1.0'
summary: Tools for debugging Edge
description: |
  Tools for debugging Edge.

grade: devel
confinement: strict

apps:
  test-bootstrap:
    command: bin/test-bootstrap.sh
    plugs:
      - network
  test-lwm2m:
    command: bin/test-lwm2m.sh
    plugs:
      - network
  daemon:
    command: bin/daemon.sh
    plugs:
      - network
      - network-observe
    daemon: simple
    restart-condition: always
    restart-delay: 5s

parts:
  credentials:
    plugin: dump
    source: credentials/
    organize:
      '*': credentials/
  scripts:
    plugin: dump
    source: scripts/
    organize:
      daemon.sh: bin/
      test-bootstrap.sh: bin/
      test-lwm2m.sh: bin/
