name: pelion-edge-tools
base: core20
version: '0.9'
summary: Tools for debugging Pelion Edge
description: |
  Tools for debugging Pelion Edge.

grade: devel
confinement: strict

apps:
  test-bootstrap:
    command: bin/test-bootstrap.sh
    plugs:
      - network
  test-lwm2m:
    command: bin/test-lwm2m.sh
    plugs:
      - network

parts:
  credentials:
    plugin: dump
    source: credentials/
    organize:
      '*': credentials/
  scripts:
    plugin: dump
    source: scripts/
    organize:
      test-bootstrap.sh: bin/
      test-lwm2m.sh: bin/
